### ISSUE TITLE
the recevid IR value is confusing

### ISSUE THREAD

**Issue by masudpce** [Nabil0036/obstacle#6]
"a==0"
or "b ==0"
is confusing. 
1. what does 0 or 1 means here ?
2. how the sensor is connected to the Arduino pin? source or sink ?

https://github.com/Nabil0036/obstacle/blob/35b8e1455e54410b1075eae5252941978997a293/obstacle.ino#L29-L43

**Comment by iftekherhossain** [comment]
i am clearing that issue
